version: '3.2'
services:

  postgres:
    image: postgres:10
    environment:
      POSTGRES_DB: backend_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: some_password
    volumes:
      - database-data:/var/lib/postgresql/data/ 
    ports:
      - 5432:5432
    networks:
      - postgres     
 

volumes:

  database-data:
    driver: local  

networks:

  postgres:
    driver: bridge  
